yarnPath: .yarn/releases/yarn-4.0.0-rc.37.cjs
enableGlobalCache: true
logFilters:
  - code: YN0061
    level: discard
  - code: YN0060
    level: discard
  - code: YN0002
    level: discard
nodeLinker: node-modules
nmHoistingLimits: workspaces
preferAggregateCacheInfo: true
changesetIgnorePatterns:
  - .yarn/**
