name: Release
on:
  release:
    types: [ published ]

env:
  APP_VERSION: ${{ github.event.release.tag_name }}
  JETBRAINS_TOKEN: ${{ secrets.JETBRAINS_TOKEN }}

jobs:
  publish:
    name: Publish to Jetbrains Marketplace
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Publish to JetBrains marketplace
        run: sh gradlew publishPlugin
        working-directory: src/intellij
